# Number of days of inactivity before an issue becomes stale
daysUntilStale: 300
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 60
# Issues with these labels will never be considered stale
exemptLabels:
  - ":safety_pin: pinned"
# Label to use when marking an issue as stale
staleLabel: ":hourglass: stale"
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed in two months if no further activity occurs.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been automatically closed because of inactivity.
  You can support the Cucumber core team on [opencollective](https://opencollective.com/cucumber).
