extends:
  - standard-with-typescript
  - "plugin:prettier/recommended"
  - "prettier/@typescript-eslint"
parserOptions:
  project: './tsconfig.json'
rules:
  prettier/prettier:
    - error
    - trailingComma: es5
      singleQuote: true
      semi: false