env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - prettier
globals:
  afterEach: false
  beforeEach: false
  createMock: false
  describe: false
  expect: false
  it: false
  sinon: false
parser: babel-eslint
parserOptions:
  sourceType: module
plugins:
  - babel
  - prettier
rules:
  babel/new-cap: error
  complexity: error
  eqeqeq: [error, always]
  no-await-in-loop: error
  no-negated-condition: error
  no-nested-ternary: error
  no-plusplus: error
  no-shadow: error
  no-unneeded-ternary: [error, {defaultAssignment: false}]
  no-var: error
  object-shorthand: [error, always]
  prettier/prettier:
    - error
    - trailingComma: none
      singleQuote: true
      semi: false
