env:
  browser: true
  es6: true
  node: true
extends:
  - standard
  - prettier
globals:
  afterEach: false
  beforeEach: false
  createMock: false
  describe: false
  expect: false
  it: false
  sinon: false
parser: babel-eslint
parserOptions:
  sourceType: module
plugins:
  - babel
  - prettier
rules:
  prettier/prettier:
    - error
    - trailingComma: none
      singleQuote: true
      semi: false
