extends:
  - 'eslint:recommended'
  - 'plugin:import/typescript'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
plugins:
  - import
  - node
  - '@typescript-eslint'
  - prettier
rules:
  'prettier/prettier': 'error'
  'no-console': 'error'
  # requires strictNullChecks compiler option, produces many errors with messages objects
  '@typescript-eslint/strict-boolean-expressions': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-inferrable-types': off
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/ban-types': off
  '@typescript-eslint/no-unused-vars': [error, { "argsIgnorePattern": "^_" }]
