import { DIALECTS } from 'gherkin'

/**
 * In cases when a scenario is generated by a scenario outline
 * the scenario's keyword equals to the scenario outline's keyword.
 * The function replaces the scenario's keyword with the first keyword
 * in the scenario keyword's list for the specified language.
 */
export function normalizeScenarioKeyword(keyword, language) {
  const keywords = DIALECTS[language]['scenarioOutline']
  if (keywords.find(k => k === keyword)) {
    keyword = DIALECTS[language]['scenario'][0]
  }
  return keyword
}
